const songs = [{artist: 'Ottorino Respighi', name: '6 Pieces for Piano No. 2 (Canone)', youtubeId: 'P9eB1QzpwaQ'},
{artist: 'Ludwig van Beethoven', name: 'Fur Elise', youtubeId: '_mVW8tgGY_w'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 39 No. 3', youtubeId: '8XBgLOeXOD0'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 16 in C Major (K. 545, Facile)', youtubeId: '19Am6J22AK8'},
{artist: 'Frederic Chopin', name: 'Trois Grandes Valses Brillantes Op. 34 No. 3 (Waltz)', youtubeId: 'MV6aVO8hsVQ'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 14 in C Minor (K. 457)', youtubeId: 'hKHfRV19hw8'},
{artist: 'Scott Joplin', name: 'The Entertainer', youtubeId: 'fPmruHc4S9Q'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 2', youtubeId: 'E9S2CfDwNAg'},
{artist: 'Frederic Chopin', name: 'Waltz Op. 42 (Two-Four)', youtubeId: 'j0qEH09suZs'},
{artist: 'Frederic Chopin', name: 'Rondo a la Mazur Op. 5 in F Major', youtubeId: '_XCNKEhWNh0'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 7 in C Major (K. 309)', youtubeId: '1yCGTrvxSVY'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 3 (Tristesse)', youtubeId: 'rcDb8-aX26U'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 9 No. 2', youtubeId: 'Nu48Z45ibxQ'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 9 in E Major (Op. 14)', youtubeId: 'jiRbJ26qw5c'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 27 No. 1', youtubeId: 'QAcAWWU_0mE'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 15 in G Major', youtubeId: 'gNlXYLsC_Vs'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 18 (Suicide)', youtubeId: '0cCMFAYYYow'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 1 (Brouillards)', youtubeId: 'S_RMhIJARgY'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 4 in C# Minor', youtubeId: 'wCB97STEYr8'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 12 (Ocean)', youtubeId: 'EkLjfTrbRww'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 33 No. 6', youtubeId: '6Oe2TzZoiGM'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 14 in F# Minor', youtubeId: 'HZMDhZRf9FA'},
{artist: 'Robert Schumann', name: 'Fantasie in C Op. 17', youtubeId: 'XZ7hE4lQAYs'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 5', youtubeId: 'M8RyWFA7PSY'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 2', youtubeId: '9xK4747tyt8'},
{artist: 'Johannes Brahms', name: '6 Klavierstucke Op. 118 No. 6 (Intermezzo in E-flat Minor)', youtubeId: '4AQ2J_LgfVo'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 2 (Voiles)', youtubeId: 't_lsFxsAJEU'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 12 (Chasse-Neige)', youtubeId: '5PqWXDo9TIw'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 10', youtubeId: 't3SGma5VPx8'},
{artist: 'Franz Liszt', name: 'Mephisto Polka', youtubeId: 'PEInHhTac24'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 2 (The Bees)', youtubeId: 'lEhqzRxS_80'},
{artist: 'Sergei Rachmaninoff', name: 'Nocturne No. 3', youtubeId: 'xnDIw8yJHMA'},
{artist: 'Erik Satie', name: 'Gnossienne No. 2', youtubeId: 'tCjhxNBHU0A'},
{artist: 'Frederic Chopin', name: 'Berceuse Op. 57', youtubeId: 'v1CXY5NHvms'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 20 (Funeral March)', youtubeId: 'jKrPsyV-5MA'},
{artist: 'Franz Schubert', name: 'Wanderer Fantasy in C Major', youtubeId: 'Vy_HeH-pRfI'},
{artist: 'Maurice Ravel', name: 'Jeux d\'eau', youtubeId: 'jnKFIp7CahY'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 27 in E Minor (Op. 90)', youtubeId: 'Fi9jVgP94ZA'},
{artist: 'Claude Debussy', name: 'Images No. 3 (Mouvement)', youtubeId: 'zjJQrglLvXY'},
{artist: 'Sergei Rachmaninoff', name: 'Morceaux de Fantaisie No. 3 (Melodie)', youtubeId: 'vwVa1nOn4sc'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 10 (Scenes from Childhood - Almost Too Serious)', youtubeId: 'nCqxtediy54'},
{artist: 'Erik Satie', name: 'Gnossienne No. 4', youtubeId: 'JE8ReAAcZjU'},
{artist: 'Sergei Prokofiev', name: 'Piano Sonata No. 2 in D Minor', youtubeId: 'PZN7XLKzLDI'},
{artist: 'Frederic Chopin', name: 'Polonaise Op. 26 No. 1', youtubeId: 'Nedn2E5g2cM'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 1 (Reunion)', youtubeId: 'NZUCq5GfsQ4'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 9', youtubeId: 'OGlTm7cZOms'},
{artist: 'Claude Debussy', name: 'Images No. 5 (Et la lune descend sur le temple qui fut)', youtubeId: 'P0-LwlHXhLw'},
{artist: 'Sergei Rachmaninoff', name: 'Moment Musicaux No. 6', youtubeId: '3f96TImIU1I'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 2 (Scenes from Childhood - A Curious Story)', youtubeId: '2vU92xoEVwU'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 8', youtubeId: 'MR8bPMdFpJ8'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 5 (Bruyeres)', youtubeId: 'RhzeRTnn2lY'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 8', youtubeId: 'HU1cK293_CI'},
{artist: 'Frederic Chopin', name: 'Three Waltzes Op. 64 No. 1 (Minute Waltz)', youtubeId: 'OoX6ZTUd3Vo'},
{artist: 'Ottorino Respighi', name: '6 Pieces for Piano No. 6 (Intermezzo)', youtubeId: 'dU6VzjQzHzc'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 33 No. 4', youtubeId: '_s-hEZDe5G4'},
{artist: 'Sergei Prokofiev', name: 'Piano Sonata No. 4 in C Minor', youtubeId: 'KYm6Oqn0XNg'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 23 in B Major', youtubeId: 'ongruzgfdX0'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 2 (Chromatic)', youtubeId: 'A3j57AdHSvg'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 10 (La Cathedrale engloutie)', youtubeId: 'gNGnDscDyTc'},
{artist: 'Franz Liszt', name: 'Consolation No. 6', youtubeId: 'WKo-o1xZ6bk'},
{artist: 'Claude Debussy', name: 'Children\'s Corner Mvt. 6 (Golliwogg\'s Cakewalk)', youtubeId: '2RBGOabwv-Y'},
{artist: 'Franz Schubert', name: 'Impromptu Op. 142 No. 2 (A-flat Major)', youtubeId: 'GP2jiupyu90'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 39 No. 1', youtubeId: 'G7MBOGlepPE'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 11 (Arpeggio)', youtubeId: 'eG1Mv892-lE'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 11 (La danse de Puck)', youtubeId: 'Vc32-bFg80Y'},
{artist: 'Franz Liszt', name: 'Benediction de Dieu dans la solitude', youtubeId: 'K03xMG7fdQ4'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 8 in D# Minor', youtubeId: 'MAJySJMDYqs'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 11 (Winter Wind)', youtubeId: 'Dsg85_wsl3w'},
{artist: 'John Cage', name: '4\'33', youtubeId: 'gN2zcLBr_VM'},
{artist: 'Franz Liszt', name: 'Sonetto 123 del Petrarca', youtubeId: 'UUPHRymh9LE'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 16 (Hades)', youtubeId: 'Qphpgy3EmrM'},
{artist: 'Claude Debussy', name: 'Arabesque No. 1', youtubeId: 'XMVmQAW0CM8'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 6 in D Minor', youtubeId: 'qdxM3M_CcRU'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 62 No. 1', youtubeId: 'Tr8QGUMJLo8'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 11 in B-flat Minor', youtubeId: 'sS5f_f7_7xs'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 18 in D Major (K. 576)', youtubeId: 'uhvzbtgSmaA'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 10 (The Night Moth)', youtubeId: 'edB-tmNHibg'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 7', youtubeId: 'cB0Sgfqd8H8'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 1 (Aeolian Harp)', youtubeId: '9XmuN9Wucto'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 2', youtubeId: 'RICGqS2UtmU'},
{artist: 'Sergei Rachmaninoff', name: 'Piano Sonata No. 1', youtubeId: '8aDZpIOAqWg'},
{artist: 'Claude Debussy', name: 'Suite Bergamasque Mvt. 2 (Menuet)', youtubeId: 'xMWxieAQF8g'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 9', youtubeId: 'A0umohcLS1I'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 7 (Eroica)', youtubeId: 'kYoIwgR0fhI'},
{artist: 'Franz Liszt', name: 'Mephisto Waltz No. 1', youtubeId: 'KJbg9V2KnD8'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 16 in G Minor', youtubeId: 'tqOWYTjm1w8'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 11', youtubeId: 'BHa5L8JBBls'},
{artist: 'Sergei Rachmaninoff', name: 'Nocturne No. 1', youtubeId: 'qw2YFUAllW0'},
{artist: 'Scott Joplin', name: 'Weeping Willow Rag', youtubeId: 'hrhgvBd5puo'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 2 (Presentiment of Death)', youtubeId: 'Ge35Qjhvj9M'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 7', youtubeId: 'mLOj75liXW0'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 48 No. 1', youtubeId: 'c94nySKKoWE'},
{artist: 'Franz Liszt', name: '3 Concert Etudes (Il Lamento)', youtubeId: 'aglz9spZ_9s'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 3 (Thou Art So Like a Flower)', youtubeId: 'mStlxA97i_o'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 11 (The Dragonfly)', youtubeId: 'fqLAu7A1y1Q'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 7 (Scenes from Childhood - Dreaming)', youtubeId: '_d8_EJ2v_yo'},
{artist: 'Erik Satie', name: 'Gnossienne No. 1', youtubeId: 'PLFVGwGQcB0'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 22 (Impatience)', youtubeId: 'RabczHZ9rts'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 23 in B Major', youtubeId: 'V0e0NrBBW2U'},
{artist: 'Franz Schubert', name: 'Impromptu Op. 142 No. 3 (B-flat Major)', youtubeId: 'H5mfwckBLWM'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 24 (The Storm)', youtubeId: 'eGSzH5qbkbc'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 39 No. 9', youtubeId: 'OVQBpJF_7DA'},
{artist: 'Franz Liszt', name: '2 Concert Etudes No. 1 (Waldesrauschen)', youtubeId: 'LjgWHcjbZDg'},
{artist: 'Frederic Chopin', name: 'Scherzo Op. 54 No. 4', youtubeId: 'dU3eMoR4hso'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 3 (Paysage)', youtubeId: 'Z9OYPpP_GZo'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 8 in A-flat Major', youtubeId: 'Z2aeNSM04Gk'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 10', youtubeId: 'tCEmVWR3dZg'},
{artist: 'Sergei Prokofiev', name: 'Piano Sonata No. 7 in B-flat Major (Stalingrad)', youtubeId: 'h21KSLqj7HA'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 3 (The Horseman)', youtubeId: 'UQf00j26SoA'},
{artist: 'Franz Schubert', name: 'Piano Sonata No. 13 in A Major', youtubeId: 'sMOupeobPOQ'},
{artist: 'Maurice Ravel', name: 'Gaspard de la Nuit No. 2 (Le Gibet)', youtubeId: 'mhpX-CyTvfw'},
{artist: 'Frederic Chopin', name: 'Rondo in E-flat Major Op. 16', youtubeId: 'CxSEdBKcQYE'},
{artist: 'Claude Debussy', name: 'Pour le Piano Mvt. 3 (Toccata)', youtubeId: 'qhN6zR3eEd0'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 9 (Butterfly)', youtubeId: '-XW6G9YdEqA'},
{artist: 'Claude Debussy', name: 'Suite Bergamasque Mvt. 1 (Prelude)', youtubeId: 'g9F4yAww9H0'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 13', youtubeId: 'QnXD1XUEOBc'},
{artist: 'Felix Mendelssohn', name: 'Songs without Words Op. 19 No. 4', youtubeId: '4p-lnBD4uhM'},
{artist: 'Franz Liszt', name: 'Reminiscences des Puritains', youtubeId: 'em2dBQMVq90'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 32 in C Minor (Op. 111)', youtubeId: 'YE2iyBRmA_g'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 6 (Des pas sur la neige)', youtubeId: 'Eym3nCRxev0'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 3 in C Major (Op. 2)', youtubeId: '3asWeutbY0c'},
{artist: 'Franz Liszt', name: '3 Concert Etudes (La Leggierezza)', youtubeId: '5bNfeukrKNE'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (June - Barcarolle)', youtubeId: 'a5Coay_ykXs'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 55 No. 1', youtubeId: 'Hxz6QZlsAIo'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 18 in G# Minor', youtubeId: '0mIMYvefxbI'},
{artist: 'Frederic Chopin', name: 'Grande Valse Brillante Op. 18 (Waltz)', youtubeId: 'LG-E4PVGQSI'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 12 in A-flat Major (Op. 26, Funeral March)', youtubeId: 'Ncs9nJNuFGA'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 8 (Sunshine)', youtubeId: 'D0f8yxbk1yk'},
{artist: 'Claude Debussy', name: 'Images No. 2 (Hommage a Rameau)', youtubeId: 'Clb7xkjQtuM'},
{artist: 'Frederic Chopin', name: 'Scherzo Op. 39 No. 3', youtubeId: 'rjmUbZ3Aumw'},
{artist: 'Franz Liszt', name: 'Jeux d\'eaux a la Villa d\'Este', youtubeId: '-w5l9KkbN70'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 6', youtubeId: '6mwSf67Obzk'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (July - Song of the Reaper)', youtubeId: 'OedJr-jNtFA'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 8 (La fille aux cheveux de lin)', youtubeId: 'KYLjHziapRs'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 22 in B-flat Minor', youtubeId: 'CL00B8TQMBQ'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 16 in G Major (Op. 31)', youtubeId: 'q7LXQVxd6xA'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 5 (Wrong Note)', youtubeId: 'LUj6n-ut8R4'},
{artist: 'Franz Schubert', name: 'Impromptu Op. 90 No. 1 (C Minor)', youtubeId: 'AJN-JnBBEGE'},
{artist: 'Erik Satie', name: 'Gymnopedie No. 1', youtubeId: 'S-Xm7s9eGxU'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 12 in D# Minor', youtubeId: 'uz3TqZtAkeQ'},
{artist: 'Scott Joplin', name: 'Solace - A Mexican Serenade', youtubeId: 'oLNORRrRyMQ'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 24 in B Minor', youtubeId: 'zTzPP3Lcaqw'},
{artist: 'Frederic Chopin', name: 'Scherzo Op. 31 No. 2', youtubeId: 'z_MwPdr7WXQ'},
{artist: 'Frederic Chopin', name: 'Polonaise Op. 71 No. 2', youtubeId: 'YO7AyYTW9Sw'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 21 (Sunday)', youtubeId: 'yIwTQmBdeoY'},
{artist: 'Franz Liszt', name: 'Mephisto Waltz No. 3', youtubeId: 'Yhj3yc8VQkQ'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (November - Troika)', youtubeId: 'y8rbCIuqgmY'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 4', youtubeId: 'Y4JRy0ns1lw'},
{artist: 'Franz Liszt', name: 'Liebestraume No. 3', youtubeId: 'KpOtuoHL45Y'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 4 (Torrent)', youtubeId: 'XIKdCTmcTLs'},
{artist: 'Frederic Chopin', name: 'Rondo in C Minor Op. 1', youtubeId: 'WXcfIegR-F8'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 9', youtubeId: 'wUNpATwAYFA'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 37 No. 2', youtubeId: 'wmy0fY6Jki0'},
{artist: 'Maurice Ravel', name: 'Miroirs No. 3 (Une Barque sur l\'ocean)', youtubeId: 'bTYUyDjVCRU'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 5 (Les collines d\'Anacapri)', youtubeId: 'WFfXnhJ5GzU'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 4 in B Major', youtubeId: 'wcKvmkTXjx0'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 12 (Revolutionary)', youtubeId: 'w2vLEQno9Ks'},
{artist: 'Claude Debussy', name: 'Reverie', youtubeId: 'vqXwzUW_fhM'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 10 (Preludio)', youtubeId: '_eG8vW9Jils'},
{artist: 'Franz Schubert', name: 'Impromptu Op. 90 No. 4 (A-flat Major)', youtubeId: 'V0z7mUV5rSc'},
{artist: 'Frederic Chopin', name: 'Allegro de Concert Op. 46', youtubeId: '_OBPsBjjxb8'},
{artist: 'Frederic Chopin', name: 'Fantaisie in F Minor Op. 49', youtubeId: 'txoJC2vaeFE'},
{artist: 'Maurice Ravel', name: 'Miroirs No. 2 (Oiseaux Triste)', youtubeId: 'trN06fsSRdM'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 1 in C Major', youtubeId: 'tkNzx7hXu_U'},
{artist: 'Sergei Rachmaninoff', name: 'Piano Sonata No. 2', youtubeId: 'TH7YE7JWw1U'},
{artist: 'Franz Liszt', name: 'Reminiscences des Huguenots', youtubeId: 'Tc-WkvJWTJ8'},
{artist: 'Franz Liszt', name: 'Mephisto Waltz No. 2', youtubeId: 'Sxg_KlbBC78'},
{artist: 'Sergei Rachmaninoff', name: 'Morceaux de Fantaisie No. 1 (Elegie)', youtubeId: 'sTUxrPJfpqk'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 2 in C Minor', youtubeId: 'Sq18ziIaO7U'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 7 (Toccata)', youtubeId: 'RZWjOzBl0zU'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 4 (Les fees sont d\'exquises danseuses)', youtubeId: 'rr9lk3WJsv0'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 7 (Ce qu\'a vu le vent d\'Ouest)', youtubeId: 'RNcvnOwxFrA'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 14 in F# Minor', youtubeId: 'RjAQLU23keI'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 24 in B Minor', youtubeId: 'pSaMSsMukx8'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 25 in G Major (Op. 79, Cuckoo)', youtubeId: 'QovNsObNtVo'},
{artist: 'Frederic Chopin', name: 'Barcarolle Op. 60', youtubeId: 'q9umBE2Gn7Q'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 39 No. 6', youtubeId: 'pVIfRuOZ1uo'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 8 Prelude in E-flat Minor and Fugue in D# Minor', youtubeId: 'pjLrnemeihA'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (October - Autumn\'s Song)', youtubeId: 'P_faR8r8k4g'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 2 (Feuilles mortes)', youtubeId: 'oQPv_5O_TXc'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 9 No. 3', youtubeId: 'O3Apq41rrFc'},
{artist: 'Sergei Rachmaninoff', name: 'Moment Musicaux No. 3', youtubeId: 'nop-4PTOEHc'},
{artist: 'Franz Liszt', name: 'Legende No. 2', youtubeId: 'NjSjOU-v1hU'},
{artist: 'Claude Debussy', name: 'Suite Bergamasque Mvt. 3 (Clair de Lune)', youtubeId: 'Nft7tiy5E-w'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 4 in E-flat Major (K. 282)', youtubeId: 'NButT_C1cCI'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 2 in A Major (Op. 2)', youtubeId: 'my9yp4f1lPQ'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 32 No. 2', youtubeId: 'my5OSmQZjns'},
{artist: 'Frederic Chopin', name: 'Tarantelle Op. 43', youtubeId: 'mrnPphNwa_0'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 9 (Ricordanza)', youtubeId: 'Mi_Ow9PBUks'},
{artist: 'Franz Liszt', name: 'Consolation No. 3', youtubeId: 'MfDmUk7ie6s'},
{artist: 'Franz Schubert', name: 'Piano Sonata No. 21 in B-flat Major', youtubeId: 'MAZ8PA5_gVA'},
{artist: 'Franz Liszt', name: 'Ballade No. 2', youtubeId: 'm90vsN3SjvM'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 4 in E-flat Major (Op. 7, Grande Sonata)', youtubeId: 'lLf3k5ez-l0'},
{artist: 'Felix Mendelssohn', name: 'Songs without Words Op. 19 No. 3 (Hunting Song)', youtubeId: 'lHVdJAed8_4'},
{artist: 'Claude Debussy', name: 'Arabesque No. 2', youtubeId: 'KKHeEw7whUQ'},
{artist: 'Maurice Ravel', name: 'Prelude in A Minor', youtubeId: 'v7xz3dbWXoA'},
{artist: 'Franz Liszt', name: 'Grandes etudes de Paganini No. 3 (La Campanella)', youtubeId: 'JpfbDLFSZb4'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 6 (General Lavine)', youtubeId: 'jwyV9DXpasg'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 12 (Scenes from Childhood - Child Falling Asleep)', youtubeId: 'jdSa6oHSzj0'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 1', youtubeId: '8xCR3HjYwyw'},
{artist: 'Erik Satie', name: 'Gymnopedie No. 2', youtubeId: 'IM54ja7p86U'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 12 (Minstrels)', youtubeId: 'HX065QRAtPM'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 17 in D Minor (Op. 31, Tempest)', youtubeId: 'hl_6lAvMsKE'},
{artist: 'Sergei Prokofiev', name: 'Piano Sonata No. 8 in B-flat Major', youtubeId: 'hGRWUiO37s4'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 6', youtubeId: 'gWxqGu3r9Qg'},
{artist: 'Maurice Ravel', name: 'Menuet sur le Nom de Haydn', youtubeId: 'HcUn0Roy_k8'},
{artist: 'Frederic Chopin', name: 'Ballade No. 1', youtubeId: 'G_uLCAZVh5Y'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 21 in B-flat Major', youtubeId: 'FzwlNtcWV34'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 8 (Ondine)', youtubeId: 'fSpX3d0GEHU'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 4 (Suffocation)', youtubeId: 'FDT_gtC5faQ'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 9 in G# Minor', youtubeId: 'f77orJEu2nM'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 1 (Danseuses de Delphes)', youtubeId: 'f-qmwakVFOg'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 1 in C Major', youtubeId: 'ezZdbzreNcs'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 10 in D-flat Major', youtubeId: 'EZ0FeqTvedo'},
{artist: 'Maurice Ravel', name: 'Miroirs No. 5 (La Vallee des Cloches)', youtubeId: 'XnTmtjO6IKI'},
{artist: 'Ottorino Respighi', name: '6 Pieces for Piano No. 1 (Valse Cassarate)', youtubeId: 'coogjOA1a_4'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 3 in C# Major', youtubeId: 'cmkgl2G9qVo'},
{artist: 'Maurice Ravel', name: 'Pavane Pour une Infante Defunte', youtubeId: 'eGybwV3U9W8'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 18 (Ungarische Ausstellung in Budapest)', youtubeId: 'c_D3rPtXXu0'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 7 in E-flat Major', youtubeId: 'AbvJ35CDulg'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (April - The Snowdrop)', youtubeId: 'GjlQ8fSZr1A'},
{artist: 'Ottorino Respighi', name: '6 Pieces for Piano No. 4 (Minuetto)', youtubeId: 'AwFtyAyBYRU'},
{artist: 'Sergei Prokofiev', name: 'Piano Sonata No. 1 in F Minor', youtubeId: 'APxweGUCqIs'},
{artist: 'Frederic Chopin', name: 'Ballade No. 2', youtubeId: 'AnWrFWUJWTI'},
{artist: 'Claude Debussy', name: 'Children\'s Corner Mvt. 3 (Serenade for the Doll)', youtubeId: 'aDZwQFBjm1o'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 21 in B-flat Major', youtubeId: '9U0OgPsBc30'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 19 in A Major', youtubeId: '9MN-h6loiiI'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 7 in D Major (Op. 10)', youtubeId: '9KilNvMTNTI'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 6 in A Major', youtubeId: '91DvEkF7B3E'},
{artist: 'Frederic Chopin', name: 'Polonaise Op. 53', youtubeId: '8QT7ITv9Ecs'},
{artist: 'Frederic Chopin', name: 'Polonaise Op. 44', youtubeId: 'poxT97Tp_hU'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 9 (Hommage a S. Pickwick Esq. P.P.M.P.C.)', youtubeId: 'X8nKxl5aG4A'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 13 in B-flat Major (K. 333)', youtubeId: '6UeMTSHvGUA'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 16 (Budapest Munkacsy-Festlichkeiten)', youtubeId: '63tgRtfO01E'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 8 in A Minor (K. 310)', youtubeId: '5TgHlfNnedk'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 9 No. 1', youtubeId: '3WmUrRMKyAM'},
{artist: 'Franz Liszt', name: '3 Concert Etudes (Un Sospiro)', youtubeId: '3JXMdpGpfBU'},
{artist: 'Erik Satie', name: 'Gnossienne No. 3', youtubeId: '3c_RU2NcJ9c'},
{artist: 'Frederic Chopin', name: 'Scherzo Op. 20 No. 1', youtubeId: '38VShqkukWY'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 11 (Les tierces alternees)', youtubeId: '-4Lmbqvi_Bk'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 2 in C Minor', youtubeId: '1GXHjxvSi24'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 33 No. 7', youtubeId: '0xeFpsF8pes'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 5 (Heroide-elegiaque)', youtubeId: '0fz2RsbqOkA'},
{artist: 'Sergei Prokofiev', name: 'Piano Sonata No. 5 in C Major', youtubeId: '8v0YHzg2IdE'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 2 in F# Minor', youtubeId: '_m0Eto4DxsM'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 21 in C Major (Op. 53, Waldstein)', youtubeId: 'lbblMw6k1cU'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 3', youtubeId: 'h9Ajw3MIt5s'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 2', youtubeId: 'ejQeimRb-ag'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 17 in A-flat Major', youtubeId: 'nFohjyRtKwU'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 10 in E Minor', youtubeId: '5uU-xntGPWA'},
{artist: 'Frederic Chopin', name: 'Piano Sonata No. 2 (Op. 35, Funeral March)', youtubeId: 'VUk3_qTTVg4'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 1', youtubeId: 'pn1qveK6z4U'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 1', youtubeId: 'Vcbw228Ea3w'},
{artist: 'Johann Sebastian Bach', name: 'Goldberg Varriations', youtubeId: 'Ah392lnFHxM'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 5', youtubeId: 'uIeprCg6M-M'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 6 in D Major (K. 284, Durnitz)', youtubeId: 'qbmAfCklg5M'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 20 in A Minor', youtubeId: 'oWOQVPtIo_E'},
{artist: 'Franz Liszt', name: 'Mephisto Waltz No. 4', youtubeId: 'SpykcZ9faiE'},
{artist: 'Franz Liszt', name: 'Consolation No. 4', youtubeId: 'BP94IN3qZiY'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 15 No. 3', youtubeId: 'pTfeTJME7-I'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 3 in B Minor', youtubeId: 'EsmTluomjrU'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 12 in F Major (K. 332)', youtubeId: 'RkCbGAWwZZg'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 9 (La serenade interrompue)', youtubeId: 'BduU-1j5XaA'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Fantasia in D Minor (K. 397)', youtubeId: '1BkZ8ci8_k4'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 15 in G Major', youtubeId: '_wypF6x4efw'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 3 (La puerta del Vino)', youtubeId: 'U1pylelfaHc'},
{artist: 'Erik Satie', name: 'Gnossienne No. 5', youtubeId: 'VqTe1-7JATA'},
{artist: 'Franz Schubert', name: 'Piano Sonata No. 20 In A Major', youtubeId: '5I4EbVrTU_I'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 4 (Scenes from Childhood - Pleading Child)', youtubeId: 'nUqeWz4ML2U'},
{artist: 'Franz Liszt', name: 'Reminiscences de Robert le Diable', youtubeId: 'Jvo8lJ1GOdA'},
{artist: 'Ludwig van Beethoven', name: 'Rondo a Capriccio Op. 129 (Rage Over a Lost Penny)', youtubeId: '8XFMZs_7nOA'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 13 (Scenes from Childhood - The Poet Speaks)', youtubeId: 'PNSq5utKIq4'},
{artist: 'Franz Liszt', name: 'Liebestraume No. 1', youtubeId: 'O2U59xsSgIE'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 8', youtubeId: 'RU1csd7QSwM'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 27 No. 2', youtubeId: 'WJ8RVjm49hE'},
{artist: 'Felix Mendelssohn', name: 'Songs without Words Op. 19 No. 2', youtubeId: '_-n_wbCxabY'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 13 in F# Major', youtubeId: 'e58SLSzq3kI'},
{artist: 'Sergei Rachmaninoff', name: 'Moment Musicaux No. 5', youtubeId: 'GSE_vo9xhro'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 11 in A Major (K. 331)', youtubeId: '6GezrRPNRrw'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 1 in C# Major', youtubeId: 'LV5KdR4t0Go'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 5 (Uncertainty)', youtubeId: 'PwwO-TJT5dY'},
{artist: 'Franz Schubert', name: 'Impromptu Op. 90 No. 2 (E-flat Major)', youtubeId: 'pGbh_oAwuOE'},
{artist: 'Franz Schubert', name: 'Piano Sonata No. 18 in G Major', youtubeId: 'bX_IjA3x_rw'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 13 (Loss)', youtubeId: 'LWYqBms-OBE'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 33 No. 2', youtubeId: 'vCyURa9i3ho'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (December - Yuletide)', youtubeId: 'U-FGZ5InUNc'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Fantasia in C Minor (K. 475)', youtubeId: 'wu5ivRKjpls'},
{artist: 'Franz Schubert', name: 'Piano Sonata No. 19 in C Minor', youtubeId: '_OEaXf8uZUg'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 8 (Scenes from Childhood - At the Fireside)', youtubeId: 'LdLYWM7gREE'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 11 (Harmonies du Soir)', youtubeId: 'aDscu30GBow'},
{artist: 'Claude Debussy', name: 'Images No. 4 (Cloches a travers les feuilles)', youtubeId: 'Z9RxKTXEFaA'},
{artist: 'Johann Pachelbel', name: 'Canon in D', youtubeId: 'rNsgHMklBW0'},
{artist: 'Ludwig van Beethoven', name: 'Rondo in C Op. 51 No. 1', youtubeId: '-hde6-oAorQ'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 5 (Black Keys)', youtubeId: 'gqHL2nvWs2U'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 5 in D Major', youtubeId: 'K_85VWhfSRA'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 4', youtubeId: 'MnkN-BVWC3s'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 28 in A Major (Op. 101)', youtubeId: 'n74kKqwWViU'},
{artist: 'Franz Schubert', name: 'Impromptu Op. 90 No. 3 (G-flat Major)', youtubeId: 'CyzUc2vC4JI'},
{artist: 'Claude Debussy', name: 'Images No. 1 (Reflets dans l\'eau)', youtubeId: 'VY3bzXAUedc'},
{artist: 'Sergei Rachmaninoff', name: 'Morceaux de Fantaisie No. 4 (Polichinelle)', youtubeId: 'Snr7nQBTwyM'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 5 (Scenes from Childhood - Happy Enough)', youtubeId: 'y1hiChMn5e0'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 4 (Paganini)', youtubeId: '0fz-r0fYcxE'},
{artist: 'Franz Liszt', name: 'Reminiscences de Lucrezia Borgia', youtubeId: 'e-XtfYTLi2Y'},
{artist: 'Franz Schubert', name: 'Piano Sonata No. 17 in D Major', youtubeId: '1kmeAMlPy2s'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 12', youtubeId: 'ufNMkrPeJFU'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 9 (Vision)', youtubeId: '0zLG274eUsw'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 9 in E Major', youtubeId: 'EMEITKQI7ao'},
{artist: 'Johannes Brahms', name: '6 Klavierstucke Op. 118 No. 1 (Intermezzo in A Minor)', youtubeId: '--dFka8hrzo'},
{artist: 'Felix Mendelssohn', name: 'Songs without Words Op. 19 No. 6 (Venetian Gondellied)', youtubeId: 'wPiFPbqRqo0'},
{artist: 'Scott Joplin', name: 'Stoptime Rag', youtubeId: 'gTrXnpQnwBM'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 11 in F Major', youtubeId: 'njXeHu5znZ0'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 72 No. 1', youtubeId: 'S8e2h7Iu1NA'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 39 No. 2', youtubeId: 'tZ24UHRJaa8'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 17 in B-flat Major (K. 570)', youtubeId: 'Vdnj4pc4HWE'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 20 in G Major (Op. 49)', youtubeId: 'W7WpjF2VILE'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 11 (Scenes from Childhood - Frightening)', youtubeId: 'xmIjGnogxSs'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 11 in B-flat Major (Op. 22)', youtubeId: '0_5iQCV62S4'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 8 (Desperation)', youtubeId: 'Z9ccGqrqcmA'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 5 in E Major', youtubeId: 'YeWAkGqbyWE'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 10', youtubeId: 'b2IeqQMXMJo'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 12 in F Minor', youtubeId: '77BWICJAXe4'},
{artist: 'Claude Debussy', name: 'Children\'s Corner Mvt. 2 (Jimbo\'s Lullaby)', youtubeId: 'FW8ZoeMp8L8'},
{artist: 'Felix Mendelssohn', name: 'Songs without Words Op. 19 No. 1', youtubeId: 'RIU70B6K7Ls'},
{artist: 'Sergei Rachmaninoff', name: 'Nocturne No. 2', youtubeId: 'SPNIFXz4ozY'},
{artist: 'Franz Liszt', name: '2 Concert Etudes No. 2 (Gnomenreigen)', youtubeId: 'gWs5jqRcT_4'},
{artist: 'Erik Satie', name: 'Je te veux', youtubeId: 'wbT9DeULzU4'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 30 in E Major (Op. 109)', youtubeId: '8JZGiY--2LM'},
{artist: 'Sergei Prokofiev', name: 'Piano Sonata No. 3 in A Minor', youtubeId: 'PGRls_Kjt9I'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 39 No. 4', youtubeId: 'FMcLTw8KTI8'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 1', youtubeId: '4MU_lmwIPwM'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 8 (Wilde Jagd)', youtubeId: 'U0VSKRdtHI8'},
{artist: 'Franz Liszt', name: 'Reminiscences de Norma', youtubeId: 'XEkDsUrmFC4'},
{artist: 'Franz Schubert', name: 'Piano Sonata No. 14 in A Minor', youtubeId: '7tOwEDVaRfA'},
{artist: 'Frederic Chopin', name: 'Piano Sonata No. 1 (Op. 4)', youtubeId: 'bjvu9Rd4rTA'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 19 in G Minor (Op. 49)', youtubeId: 'yqnwJmzXkac'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 29 in B-flat Major (Op. 106, Hammerklavier)', youtubeId: 'erD1Yy-4F5M'},
{artist: 'Frederic Chopin', name: 'Polonaise Op. 40 No. 1 (Military)', youtubeId: 'PC9-35ZPKn8'},
{artist: 'Franz Schubert', name: 'Piano Sonata No. 16 in A Minor', youtubeId: '9FYftb9J1ww'},
{artist: 'Scott Joplin', name: 'Ragtime Dance', youtubeId: 'unGmMmD8kPQ'},
{artist: 'Claude Debussy', name: 'Children\'s Corner Mvt. 4 (The Snow Is Dancing)', youtubeId: 'D7e8YDRQkgA'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 24 in F# Major (Op. 78, a Therese)', youtubeId: 'CfiiRZvTVeU'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (August - Harvest)', youtubeId: 'lBWOeXaBe2U'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 6 (Thirds)', youtubeId: 'ebThZOcx2io'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 7 (The Polish Dancer)', youtubeId: 'Wy7ArsZHRks'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 10 in C Major (K. 330)', youtubeId: 'vV6F_QWp23o'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 15 in D Major (Op. 28, Pastoral)', youtubeId: 'oUmrX1xO1ms'},
{artist: 'Ludwig van Beethoven', name: 'Diabelli Variations', youtubeId: 'dokkniOwSlQ'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 55 No. 2', youtubeId: 'VuiEmZYi5BM'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 62 No. 2', youtubeId: '7jvpzDfYyOU'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 8 in C Minor (Op. 13, Pathetique)', youtubeId: 'M_124D_7KoU'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (March - Song of the Lark)', youtubeId: 'nW4-ndHqUqQ'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 4 (Mazeppa)', youtubeId: 'L3MjC7VSAM0'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 15 No. 1', youtubeId: 'FrKo6AFUhUQ'},
{artist: 'Franz Liszt', name: 'Grandes etudes de Paganini No. 4', youtubeId: 'Tkh62-dlUzA'},
{artist: 'Franz Schubert', name: 'Impromptu Op. 142 No. 1 (F minor)', youtubeId: '70__XraXnkE'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 3', youtubeId: 'CcQOqISNzWQ'},
{artist: 'Johann Pachelbel', name: 'Chaconne in F Minor', youtubeId: 'PrLLEkqICEI'},
{artist: 'Frederic Chopin', name: 'Three Waltzes Op. 64 No. 3', youtubeId: 'Dmzx7Psjm0M'},
{artist: 'Frederic Chopin', name: 'Ballade No. 3', youtubeId: 'CYaKgr3gGhE'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 10 (Canope)', youtubeId: 'aiz56rW7dj4'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 12 (Feux d\'artifice)', youtubeId: 'b7VkEFKH9YM'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 39 No. 7', youtubeId: '2OVU88gDBUM'},
{artist: 'Franz Liszt', name: 'Grandes etudes de Paganini No. 5 (La Chasse)', youtubeId: 'T858oqTGuZg'},
{artist: 'Franz Liszt', name: 'Consolation No. 5', youtubeId: 'NVpZqDWx0Tc'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 13', youtubeId: 'lyaKsD5PfoU'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 23 (A Pleasure Boat)', youtubeId: '8Scc87gksWY'},
{artist: 'Maurice Ravel', name: 'Gaspard de la Nuit No. 3 (Scarbo)', youtubeId: 'd47dqPYMbGI'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 19 (Heartfelt Happiness)', youtubeId: 'bdEqbeFxLwM'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 6 (Lament)', youtubeId: 'XMiSndwL97o'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 22 in B-flat Minor', youtubeId: 'ngtgxv2farY'},
{artist: 'Ottorino Respighi', name: '6 Pieces for Piano No. 5 (Studio)', youtubeId: 'bttLqX0cnMo'},
{artist: 'Glinka/Balakirev', name: 'The Lark', youtubeId: 'IgK9qT1pwpM'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 13 in F# Major', youtubeId: 'lJCpUW1Q1yc'},
{artist: 'Schumann/Liszt', name: 'Liebeslied (Widmung)', youtubeId: '-5_jzx1mPLA'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 9 (Pesther Carneval)', youtubeId: 'yNg57hqJhA8'},
{artist: 'Alexander Scriabin', name: 'Etudes Op. 8 No. 7 in B-flat Minor', youtubeId: 'tAaiWy6CTVU'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 14 in C# Minor (Op. 27, Moonlight)', youtubeId: 'K5-IqJZPxQY'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 33 No. 8', youtubeId: 'awpqpq8a3ds'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 1 (Waterfall)', youtubeId: 'nMM6h9Yf348'},
{artist: 'Franz Liszt', name: 'Grandes etudes de Paganini No. 2', youtubeId: 'paxKueB6y3k'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 18 in E-flat Major (Op. 31, The Hunt)', youtubeId: 'aBupTI59nq4'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 32 No. 1', youtubeId: 'BhIP4hDBp-E'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (September - The Hunt)', youtubeId: 'yfLzVX2KMrw'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 6 (Tolling Bells)', youtubeId: 'IGxL2QWyPuE'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 5 in D Major', youtubeId: 't3jFwXlE0PA'},
{artist: 'Franz Liszt', name: 'Dante Sonata', youtubeId: 'KB59i99Wxc4'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 3 in B-flat Major (K. 281)', youtubeId: 'L8UnDGLn5AY'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 5 (Feux Follets)', youtubeId: 'iL1B8wbHuWc'},
{artist: 'Claude Debussy', name: 'Children\'s Corner Mvt. 1 (Doctor Gradus ad Parnassum)', youtubeId: '06X0nvACB9Y'},
{artist: 'Frederic Chopin', name: 'Trois Grandes Valses Brillantes Op. 34 No. 1 (Waltz)', youtubeId: '19JJfIJyl5M'},
{artist: 'Sergei Rachmaninoff', name: 'Morceaux de Fantaisie No. 5 (Serenade)', youtubeId: 'HESz4ewJJqA'},
{artist: 'Sergei Rachmaninoff', name: 'Moment Musicaux No. 1', youtubeId: 'u6OlftugZl0'},
{artist: 'Wolfgang Amadeus Mozart', name: '12 Variations on \'Ah, vous dirai-je, Maman\'', youtubeId: 'nTnj1apB1o8'},
{artist: 'Frederic Chopin', name: 'Piano Sonata No. 3 (Op. 58)', youtubeId: 'xGJxmCOPFVM'},
{artist: 'Sergei Rachmaninoff', name: 'Moment Musicaux No. 4', youtubeId: 'xCKPH-bsTss'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 12 in F Minor', youtubeId: 'X9Z_FVjMSWc'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 6 in D Minor', youtubeId: 'QNMYHy8B7KU'},
{artist: 'Frederic Chopin', name: 'Polonaise-Fantaisie Op. 61', youtubeId: '177qJoCI9Zw'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 6 in F Major (Op. 10)', youtubeId: 'FjmzBuRnIHk'},
{artist: 'Scott Joplin', name: 'Maple Leaf Rag', youtubeId: 'ZYqy7pBqbw4'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 4', youtubeId: 'ATWU85fxD2k'},
{artist: 'Felix Mendelssohn', name: 'Songs without Words Op. 19 No. 5', youtubeId: 'sAA9Llwx-rU'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 7 (Cello)', youtubeId: 'DRsqx7ZjKRQ'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 7', youtubeId: 'V2wVeyYH1qY'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 9 in D Major (K. 311)', youtubeId: 'SZ5Jw6KNP3M'},
{artist: 'Erik Satie', name: 'Gymnopedie No. 3', youtubeId: 'jVLsLT6cvJ4'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 10 in E Minor', youtubeId: 'wp5mPL7IPMc'},
{artist: 'Frederic Chopin', name: 'Polonaise Op. 71 No. 1', youtubeId: '6YISsf23knE'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 15 (Rakoczi March)', youtubeId: 'vo6eVtLWPXc'},
{artist: 'Franz Liszt', name: 'Reminiscences de Don Juan', youtubeId: 'JI6JfJXcUjU'},
{artist: 'Ottorino Respighi', name: '6 Pieces for Piano No. 3 (Notturno)', youtubeId: 'fXDLOZLL9tU'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 11 in F Major', youtubeId: 'qYRratzEuK8'},
{artist: 'Franz Liszt', name: 'Grandes etudes de Paganini No. 6', youtubeId: '7ZEf5VBhmpo'},
{artist: 'Frederic Chopin', name: 'Three Waltzes Op. 64 No. 2', youtubeId: 'VyBxps3BgYc'},
{artist: 'Johannes Brahms', name: '6 Klavierstucke Op. 118 No. 2 (Intermezzo in A Major)', youtubeId: '20Gb0JcviRA'},
{artist: 'Johannes Brahms', name: '6 Klavierstucke Op. 118 No. 5 (Romanze in F Major)', youtubeId: 'BVqrHzT4Xxs'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 39 No. 5', youtubeId: 'z_0oEBg2aHg'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 17 (A Scene on the Place do Notre-Dame de Paris)', youtubeId: 'NczMe1zdreg'},
{artist: 'Franz Liszt', name: 'Sonetto 47 del Petrarca', youtubeId: 'c8Jbi5mEO-I'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 4 in C# Minor', youtubeId: 'zdD_QygwRuY'},
{artist: 'Franz Liszt', name: 'Ballade No. 1', youtubeId: 'yt2Dmg4ebh8'},
{artist: 'Nikolai Rimsky-Korsakov', name: 'Flight of the Bumblebee (arr. Rachmaninoff)', youtubeId: 'EgtExoc_Zfk'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 17 in A-flat Major', youtubeId: 'gCL5Zvnt0TU'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 9 in E Major', youtubeId: 'KnRBTi-yJN0'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 2 No. 7 in E-flat Major', youtubeId: 'ECGZUM3MTHw'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 19', youtubeId: 'eJAUJLQT4vA'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 48 No. 2', youtubeId: 'GxbglzMV6hg'},
{artist: 'Sergei Rachmaninoff', name: 'Variations on a Theme of Corelli', youtubeId: 'oILLr5Lg9OI'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 9 (Scenes from Childhood - Knight of the Hobbyhorse)', youtubeId: 'DbWI-8wJxuU'},
{artist: 'Claude Debussy', name: 'Images No. 6 (Poissons d\'or)', youtubeId: 'PyCPPofdfCE'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 11', youtubeId: '5XXb6m91Edw'},
{artist: 'Franz Liszt', name: 'Consolation No. 1', youtubeId: 'z874wc7jkjw'},
{artist: 'Maurice Ravel', name: 'Gaspard de la Nuit No. 1 (Ondine)', youtubeId: 'T_-1qMPDf-A'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 15 in F Major (K. 533/494)', youtubeId: 'u81upBI1UPc'},
{artist: 'Maurice Ravel', name: 'Miroirs No. 4 (Alborada del Gracioso)', youtubeId: 'nz58NLTJtwE'},
{artist: 'Frederic Chopin', name: 'Etude Op. 10 No. 10', youtubeId: 'xtgywzzc5cA'},
{artist: 'Frederic Chopin', name: 'Fantaisie Impropmptu Op. 66', youtubeId: '75x6DncZDgI'},
{artist: 'Claude Debussy', name: 'Pour le Piano Mvt. 1 (Prelude)', youtubeId: 'sqXOWjihLLA'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 6 (Scenes from Childhood - An Important Event)', youtubeId: 'OeyvF659He4'},
{artist: 'Sergei Rachmaninoff', name: 'Moment Musicaux No. 2', youtubeId: 'vUnhMtfjAHM'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 17', youtubeId: '84DwOPCCBjY'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 39 No. 8', youtubeId: 'izIAEimMSPc'},
{artist: 'Erik Satie', name: 'Gnossienne No. 6', youtubeId: '-S089zAHE-E'},
{artist: 'Johannes Brahms', name: '6 Klavierstucke Op. 118 No. 4 (Intermezzo in F Minor)', youtubeId: 'bvN9uRObqjs'},
{artist: 'Franz Schubert', name: 'Piano Sonata No. 15 In C Major (Relique)', youtubeId: 'A4nc4fM6w-E'},
{artist: 'Frederic Chopin', name: 'Polonaise Op. 40 No. 2', youtubeId: 'vYbd5_YywCM'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 1 in F Minor (Op. 2)', youtubeId: 'o5dL-65mKe0'},
{artist: 'Frederic Chopin', name: 'Ballade No. 4', youtubeId: '7tmQSWuYwrI'},
{artist: 'Johannes Brahms', name: '6 Klavierstucke Op. 118 No. 3 (Ballade in G Minor)', youtubeId: 'GrpakH3ZqbY'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 3 in C# Major', youtubeId: 'Z-c8WG2GTaI'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 5 in C Minor (Op. 10)', youtubeId: 'GuMzYleEPRE'},
{artist: 'Claude Debussy', name: 'Pour le Piano Mvt. 2 (Sarabande)', youtubeId: 'PQL3OWs_zNU'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 2 in F Major (K. 280)', youtubeId: 'N--bkzrHu-s'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 4 (Les sons et les parfums tournent dans l\'air du soir)', youtubeId: 'wAfeDxMMOMA'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 8 (Sixths)', youtubeId: 'SoJpEyPrpl4'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 18 in G# Minor', youtubeId: 'gfrI046SU3E'},
{artist: 'Claude Debussy', name: 'Suite Bergamasque Mvt. 4 (Passepied)', youtubeId: '_hifk5F5uJM'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 23 in F Minor (Op. 57, Appassionata)', youtubeId: 'txChVYmy4BI'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 33 No. 5', youtubeId: 'D0j6ZJzyPKE'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 23 No. 6', youtubeId: '608-hlh0STk'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 10 in G Major (Op. 14)', youtubeId: 'fQqNsTUvqCY'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 33 No. 1', youtubeId: 'e5mZoS6qgsM'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 13 in E-flat Major (Op. 27, Quasi una fantasia)', youtubeId: 'ckjg-RJV-oM'},
{artist: 'Frederic Chopin', name: 'Polonaise Op. 71 No. 3', youtubeId: 'E4j2h-CXZ-4'},
{artist: 'Claude Debussy', name: 'Prelude Book 1 No. 3 (Le vent dans la plaine)', youtubeId: 'yMO5MjskewU'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 15 No. 2', youtubeId: 'XS8qe02Vx5s'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 15 (Raindrop)', youtubeId: 'exzyW7j4A1o'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 14 (Fear)', youtubeId: 'egGfLzclqK8'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 1 in C Major (K. 279)', youtubeId: '_1JkfHraqfk'},
{artist: 'Franz Liszt', name: 'Hungarian Rhapsody No. 14', youtubeId: 'qBFvTFt5xQI'},
{artist: 'Franz Liszt', name: 'Transcendental Etude No. 6 (Vision)', youtubeId: 'sapuNyxIVi8'},
{artist: 'Sergei Rachmaninoff', name: 'Morceaux de Fantaisie No. 2 (Prelude / The Bells of Moscow)', youtubeId: '14Zluhi3-DU'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 31 in A-flat Major (Op. 110)', youtubeId: '0eqDzMxQjx0'},
{artist: 'Claude Debussy', name: 'Prelude Book 2 No. 7 (La terrasse des audiences du clair de lune)', youtubeId: '4DtesmZvCxs'},
{artist: 'Frederic Chopin', name: 'Bolero Op. 19', youtubeId: 'LQt8SjISkNY'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 12', youtubeId: 'riG8At4ZHsY'},
{artist: 'Wolfgang Amadeus Mozart', name: 'Piano Sonata No. 5 in G Major (K. 283)', youtubeId: 'HLcSkRZ4-6w'},
{artist: 'Franz Liszt', name: 'Sonetto 104 del Petrarca', youtubeId: 'CnkVjsvdyoM'},
{artist: 'Frederic Chopin', name: 'Prelude Op. 28 No. 12 (The Duel)', youtubeId: 'YKSM-ix5DME'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (February - Carnival)', youtubeId: '9gNFP8mirtA'},
{artist: 'Frederic Chopin', name: 'Etude Op. 25 No. 10 (Octave)', youtubeId: 'r7zHGDxJoAU'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 22 in F Major (Op. 54)', youtubeId: 'bbB6aqHGuKM'},
{artist: 'Sergei Rachmaninoff', name: 'Etudes Tableaux Op. 33 No. 3', youtubeId: '6ei9wBgjWzo'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 1 (Scenes from Childhood - Of Foreign Lands and People)', youtubeId: 'EW1iRO3_aqY'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (May - White Nights)', youtubeId: 'fKQwyg51aCQ'},
{artist: 'Ludwig van Beethoven', name: 'Piano Sonata No. 26 in E-flat Major (Op. 81, Les Adieux)', youtubeId: 'nAapbue97JE'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 19 in A Major', youtubeId: 'TRZfA5gv-dE'},
{artist: 'Maurice Ravel', name: 'Miroirs No. 1 (Noctuelles)', youtubeId: 'nirVFe2b6Mg'},
{artist: 'Robert Schumann', name: 'Kinderszenen Op. 15 No. 3 (Scenes from Childhood - Blind Man\'s Bluff)', youtubeId: 'KWBK-B2oZBw'},
{artist: 'Frederic Chopin', name: 'Nocturne Op. 37 No. 1', youtubeId: 'EvFmw0D-DpA'},
{artist: 'Sergei Prokofiev', name: 'Piano Sonata No. 9 in C Major', youtubeId: '8TuyhdMkaCs'},
{artist: 'Sergei Rachmaninoff', name: 'Prelude Op. 32 No. 3', youtubeId: 'hMJQFZwQq8Y'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 16 in G Minor', youtubeId: 'AZKif28jMUg'},
{artist: 'Frederic Chopin', name: 'Polonaise Op. 26 No. 2', youtubeId: '51oek9sGZSg'},
{artist: 'Frederic Chopin', name: 'Trois Grandes Valses Brillantes Op. 34 No. 2 (Waltz)', youtubeId: 'PGdpRmL2XUc'},
{artist: 'Franz Schubert', name: 'Impromptu Op. 142 No. 4 (F minor)', youtubeId: 'EYtULLDLiD4'},
{artist: 'Franz Liszt', name: 'Legende No. 1', youtubeId: 'vROXOwpB5x8'},
{artist: 'Ludwig van Beethoven', name: 'Rondo in G Op. 51 No. 2', youtubeId: 'WIEq4Y6vXYE'},
{artist: 'Johann Sebastian Bach', name: 'WTC Book 1 No. 20 in A Minor', youtubeId: 'Qj4lPhfG98o'},
{artist: 'Franz Liszt', name: 'Sonata in B Minor', youtubeId: 'ZlD8EBfmKJE'},
{artist: 'Claude Debussy', name: 'Children\'s Corner Mvt. 5 (The Little Shepherd)', youtubeId: 'kusY0uYEm2w'},
{artist: 'Franz Liszt', name: 'Consolation No. 2', youtubeId: 'goRrhbXM9go'},
{artist: 'Pyotr Ilyich Tchaikovsky', name: 'The Seasons (January - At the Fireside)', youtubeId: 'P4lRfijGgm0'},
{artist: 'Sergei Prokofiev', name: 'Piano Sonata No. 6 in A Major', youtubeId: 'PAaNxVhMRp8'},
{artist: 'Franz Liszt', name: 'Grandes etudes de Paganini No. 1 (Preludio)', youtubeId: 'fu_wHWF5Z0A'},
{artist: 'Franz Liszt', name: 'Liebestraume No. 2', youtubeId: 'cvPbWWP2beM'}]

exports.songs = songs;